  name: my_first_workflow

  on:
    push:
      branches:
        - main
  jobs:
    job_one:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: greeting
          run: echo "Eyo bigman...Welcome to my world"
    job_two:
      needs: job_one
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: seeing you out
          run : echo "Good byeee and thank you for coming"
      
